name: famkid
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  logger: ^2.4.0 
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1
  device_info_plus: ^10.1.2
  connectivity_plus: ^6.0.5
  http: ^1.2.2
  mongo_dart: ^0.10.3
  barcode: ^2.2.8
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^5.1.0
  permission_handler: ^11.3.1
  flutter_datetime_picker: ^1.4.0 
  logging: ^1.2.0
  provider: ^6.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/famie_icon-removebg-preview.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/image1.png
    - assets/image2.png
    - assets/success.png
    - assets/famie_icon.png
    - assets/famie_icon-removebg-preview.png
